Add v3/email type
nocodejapan/click-types pull request #17
Opened 2023-04-12 09:32 UTC by vuongngocdiep

2023-04-13 02:15 UTC, jacklu-ncj commented on lib/services/email_service.ts
> +export interface RequestBodyV3Email {
Can you map this request to one of the service methods here? https://feathersjs.com/api/services.html

For example,  if it is implemented using update, we can call it like UpdateV3EmailRequestParams. I noticed that for create/patch/update, there is also a field called `data` which I assume it is mapped to the request body. In that case, if we want to give it a type, we can call it like `UpdateV3EmailRequestData`.

2023-04-13 02:24 UTC, fouadmen requested changes
@loan9202  @vuongngocdiep If we are not using `v2/email` endpoint, please rename `RequestBodyV3Email` to `RequestBodyEmail`

2023-04-14 01:15 UTC, jacklu-ncj commented on lib/common/notifier.ts
> +export const enum EmailTypes {
A minor thing, we should rename this to its singular form, `EmailType`, so that it would be consistent with `Locale` (not `Locales`).

2023-04-14 01:18 UTC, jacklu-ncj commented on lib/common/notifier.ts
> +  SEND_RESET_PWD = 'sendResetPwd',
`SEND_RESET_PWD` to `SEND_RESET_PASSWORD` just to be consistent with others.

2023-04-14 01:19 UTC, jacklu-ncj commented on lib/common/notifier.ts
> +  REST_PASSWORD = 'resetPwd',
minor: `resetPwd` to `resetPassword`

2023-04-14 01:21 UTC, jacklu-ncj commented on lib/common/notifier.ts
> +  PASSWORD_CHANGE = 'passwordChange',
minor: again, this should be consistent with others. We should call it `CHANGE_PASSWORD = 'changePassword'` (or, for RESET_PASSWORD we should make it PASSWORD_RESET to be consistent with this).

2023-04-14 01:23 UTC, jacklu-ncj commented on lib/common/notifier.ts
> +  VERIFY_TWO_AUTHENTICATOR = 'verifyTwoAuthenticatorSetting',
`TWO_FACTOR_AUTHENTICATION`? This one is different from others, the string representation is different from its enum representation, my suggestion
`TWO_FACTOR_AUTHENTICATION_VERIFY = twoFactorAuthenticationVerify`

What do you think?

2023-04-14 01:25 UTC, jacklu-ncj commented on lib/common/user.ts
> +export interface UserTwoAuthenticator {
Should we re-name it as `UserTwoFactorAuthenticationData`?

2023-04-14 01:25 UTC, jacklu-ncj commented on lib/common/user.ts
> +  /** The user's fill survey status. */
This comment is not correct.

2023-04-14 01:27 UTC, jacklu-ncj commented on lib/common/user.ts
> +  time?: number;
How about `expirationTime` and  should the type be `Date` instead?

2023-04-14 01:27 UTC, jacklu-ncj commented on lib/common/user.ts
> +  active: boolean;
For boolean, we should name it as `isXXX`, so this one should be called `isActive`.

2023-04-14 01:28 UTC, jacklu-ncj commented on lib/common/user.ts
> +  ec2Status: string;
Should this be a enum? It sounds like an enum to me.

2023-04-14 01:29 UTC, jacklu-ncj commented on lib/common/user.ts
> +  isDevMode: number;
`devModeStatus: string;` instead?

2023-04-14 01:29 UTC, jacklu-ncj commented on lib/common/user.ts
> +  name: string;
We probably should make a separate field for `lastName` and `firstName`.

2023-04-14 01:30 UTC, jacklu-ncj commented on lib/common/user.ts
> +  role: number;
Should this be an enum instead?

2023-04-14 01:30 UTC, jacklu-ncj commented on lib/common/user.ts
> +  beginner?: boolean;
`isBeginner`?

2023-04-14 01:34 UTC, jacklu-ncj commented on lib/common/user.ts
> +  connectId?: string | null;
Let's be explicit here, we should call it `stripeConnectId`.

2023-04-14 01:34 UTC, jacklu-ncj commented on lib/common/user.ts
> +  customerId?: string | null;
Same as above, `stripeCustomerId` instead.

2023-04-14 01:35 UTC, jacklu-ncj commented on lib/common/user.ts
> +  expert?: boolean;
`isExpert`

2023-04-14 01:37 UTC, jacklu-ncj commented on lib/common/user.ts
> +  /** The user's first login status. */
The comment should go as /** True if this is the first time user logged in. */

2023-04-14 01:38 UTC, jacklu-ncj commented on lib/common/user.ts
> + * Represents the metadata of the user.
Can you please tell me what data are part of the metadata for the user? @fouadmen

2023-04-14 01:39 UTC, jacklu-ncj commented on lib/common/user.ts
> +  profileImage?: string;
`profileImageUrl? : string | null`

2023-04-14 01:40 UTC, jacklu-ncj commented on lib/common/user.ts
> +  twoAuthenticator?: UserTwoAuthenticator;
`twoFactorAuthenticationData ?: UserTwoFactorAuthenticationData`

2023-04-14 01:41 UTC, jacklu-ncj commented on lib/common/user.ts
> +  userId?: string;
What is the difference between this field and the `id` field?

2023-04-14 01:41 UTC, jacklu-ncj commented on lib/common/user.ts
> +  verifyToken?: string;
`verificationToken`?

2023-04-14 01:41 UTC, jacklu-ncj commented on lib/common/user.ts
> +  deletedAt?: string;
All these type should be `Date | null`

2023-04-14 02:00 UTC, fouadmen commented on lib/common/user.ts
> + * Represents the metadata of the user.
@vuongngocdiep @loan9202 What is the this `UserMetadata` is for ? 
It seems to be the data we get when user first sign up into click platform. 
In this case I suggest this naming : 
```
/**
 * Represents the metadata related to user survey data.
 * /
export interface UserSurveyData {
  /** Indicates whether the user has filled out the survey. */
  hasFilledSurvey?: boolean;

  /** Stores the user's answers to the survey questions. */
  surveyAnswers?: Record<string, any>;
}
```

2023-04-17 02:51 UTC, vuongngocdiep commented on lib/common/notifier.ts
> +export const enum EmailTypes {
I  updated

2023-04-17 02:51 UTC, vuongngocdiep commented on lib/common/notifier.ts
> +  SEND_RESET_PWD = 'sendResetPwd',
I updated

2023-04-17 02:51 UTC, vuongngocdiep commented on lib/common/notifier.ts
> +  REST_PASSWORD = 'resetPwd',
I updated

2023-04-17 02:51 UTC, vuongngocdiep commented on lib/common/user.ts
> + * Represents the metadata of the user.
I updated

2023-04-17 02:51 UTC, vuongngocdiep commented on lib/common/user.ts
> +export interface UserTwoAuthenticator {
I updated

2023-04-17 02:51 UTC, vuongngocdiep commented on lib/common/user.ts
> +  /** The user's fill survey status. */
I updated

2023-04-17 02:51 UTC, vuongngocdiep commented on lib/common/user.ts
> +  active: boolean;
I updated

2023-04-17 02:51 UTC, vuongngocdiep commented on lib/common/user.ts
> +  isDevMode: number;
I updated

2023-04-17 02:51 UTC, vuongngocdiep commented on lib/common/user.ts
> +  name: string;
This name is a nickname. I think we shouldn't make a separate field for lastName and firstName.

2023-04-17 02:52 UTC, vuongngocdiep commented on lib/common/user.ts
> +  deletedAt?: string;
I updated

2023-04-17 02:52 UTC, vuongngocdiep commented on lib/common/user.ts
> +  verifyToken?: string;
I updated

2023-04-17 02:52 UTC, vuongngocdiep commented on lib/common/user.ts
> +  twoAuthenticator?: UserTwoAuthenticator;
I updated

2023-04-17 02:52 UTC, vuongngocdiep commented on lib/common/user.ts
> +  profileImage?: string;
I updated

2023-04-17 02:53 UTC, vuongngocdiep commented on lib/common/user.ts
> +  role: number;
I updated

2023-04-17 02:58 UTC, jacklu-ncj commented on lib/common/user.ts
> +  /** The user's fill survey status. */
Should this comment be something like: "True if the user enables the two factor authentication"? I would also suggest to rename this to `isEnabled`.

2023-04-17 02:59 UTC, jacklu-ncj commented on lib/common/user.ts
> +  name: string;
Then we should simply call it `nickName`.

2023-04-17 03:02 UTC, jacklu-ncj commented on lib/common/user.ts
> +  userId?: string;
I see. So the other `id` is generated by click and this `userId` is provided from the user. We should make a note and add that to the comment.

Suggestion:
```
/** User id provided by the click user whereas the other id is generated by cick
     * -maxLength: 30
     * /
  ```

2023-04-17 03:19 UTC, jacklu-ncj approved these changes

2023-04-17 04:47 UTC, fouadmen approved these changes

2023-04-17 06:03 UTC, merged