Define type for plan payment service
nocodejapan/click-types pull request #21
Opened 2023-04-27 04:50 UTC by loan9202

## Issue ID

### Purpose
- Define type for plan payment service

### Does this introduce a breaking change?

### Pull Request type

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

### How to test ?
1. Click to setting app
2. Click tab `Choose a plan`
3. Update Plan information
4. Click Next -> Subscribe or Save Button

### What to check ?
- See the chang on current plan

2023-04-27 05:29 UTC, fouadmen requested changes
@loan9202 Looks good, but please be careful about the naming, typos and be sure to follow the naming conventions of click types ;)
Thank you!

2023-04-27 05:29 UTC, fouadmen commented on lib/services/plan_payment_service.ts
> +  yearly?: boolean;
If attribute or variable is boolean use `is...`.
Also please be more specific.
```suggestion
  isYearlyPayment?: boolean;
```

2023-04-27 05:29 UTC, fouadmen commented on lib/services/plan_payment_service.ts
> +  coupon?: string;
```suggestion
  couponCode?: string;
```

2023-04-27 05:29 UTC, fouadmen commented on lib/services/plan_payment_service.ts
> +  paymentMethodId: string;
```suggestion
  stripePaymentMethodId: string;
```

2023-04-27 05:29 UTC, fouadmen commented on lib/services/plan_payment_service.ts
> +}
```suggestion
  /** The ID of the selected payment plan */
  selectedPlanId: string;
}
```

2023-04-27 05:29 UTC, fouadmen commented on lib/services/plan_payment_service.ts
> +  totalRequest: number;
Please be careful about typos
```suggestion
  /** The total number of requests for the payment plan */
  totalRequests: number;
```

2023-04-27 05:29 UTC, fouadmen commented on lib/services/plan_payment_service.ts
> +export interface PlanPaymentRequestBody {
Please follow the naming conventions on click types repo.
```suggestion
export interface CreatePlanPaymentRequestBody {
```

2023-04-27 08:37 UTC, loan9202 commented on lib/services/plan_payment_service.ts
> +  yearly?: boolean;
I updated

2023-04-27 08:37 UTC, loan9202 commented on lib/services/plan_payment_service.ts
> +  paymentMethodId: string;
I updated

2023-04-27 08:38 UTC, loan9202 commented on lib/services/plan_payment_service.ts
> +  totalRequest: number;
I updated

2023-04-27 08:38 UTC, loan9202 commented on lib/services/plan_payment_service.ts
> +export interface PlanPaymentRequestBody {
I updated

2023-04-27 08:41 UTC, loan9202 commented on lib/services/plan_payment_service.ts
> +  coupon?: string;
I updated

2023-04-28 01:15 UTC, fouadmen approved these changes
LGTM! thanks!

2023-04-28 01:43 UTC, fouadmen requested changes
I noticed this return type, please be careful with the naming, thank you !

2023-04-28 01:43 UTC, fouadmen commented on lib/services/plan_payment_service.ts
> +export type PlanPaymentResponse = Stripe.Response<Stripe.Subscription> & {
@loan9202 
I missed this one, please be careful with the naming.
```suggestion
export type CreatePlanPaymentResponse = Stripe.Response<Stripe.Subscription> & {
```

2023-04-28 06:52 UTC, loan9202 commented on lib/services/plan_payment_service.ts
> +export type PlanPaymentResponse = Stripe.Response<Stripe.Subscription> & {
I updated

2023-04-28 07:20 UTC, fouadmen approved these changes
looks good thanks 👍

2023-05-08 07:08 UTC, merged